### ISSUE TITLE
ทำ validation ของ field Device ใน controller

### ISSUE THREAD

**Issue by offoneway** [sut64/team05#36]
อ้างอิง story #4

**Comment by boomertnt210943** [comment]
ไม่ได้ใช้เนื่องจากการพิมพ์ผิด

**Comment by rinradaW** [comment]
ได้ทำ validation ของ field device ใน controller เรียบร้อยแล้ว ใน issue #38 

<img width="521" alt="Screen Shot 2565-02-12 at 20 44 13" src="https://user-images.githubusercontent.com/89482089/153713801-b9dec19a-01e2-4405-ba41-3053080e1994.png">
